/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KerbalApi.Api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class DockingPort : TBase
  {
    private DockingPortState _state;
    private long _partId;
    private double _reEngageDistance;
    private bool _hasShield;
    private bool _shielded;
    private long _dockedPart;

    /// <summary>
    /// 
    /// <seealso cref="DockingPortState"/>
    /// </summary>
    public DockingPortState State
    {
      get
      {
        return _state;
      }
      set
      {
        __isset.state = true;
        this._state = value;
      }
    }

    public long PartId
    {
      get
      {
        return _partId;
      }
      set
      {
        __isset.partId = true;
        this._partId = value;
      }
    }

    public double ReEngageDistance
    {
      get
      {
        return _reEngageDistance;
      }
      set
      {
        __isset.reEngageDistance = true;
        this._reEngageDistance = value;
      }
    }

    public bool HasShield
    {
      get
      {
        return _hasShield;
      }
      set
      {
        __isset.hasShield = true;
        this._hasShield = value;
      }
    }

    public bool Shielded
    {
      get
      {
        return _shielded;
      }
      set
      {
        __isset.shielded = true;
        this._shielded = value;
      }
    }

    public long DockedPart
    {
      get
      {
        return _dockedPart;
      }
      set
      {
        __isset.dockedPart = true;
        this._dockedPart = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool state;
      public bool partId;
      public bool reEngageDistance;
      public bool hasShield;
      public bool shielded;
      public bool dockedPart;
    }

    public DockingPort() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 2:
            if (field.Type == TType.I32) {
              State = (DockingPortState)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I64) {
              PartId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 21:
            if (field.Type == TType.Double) {
              ReEngageDistance = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 22:
            if (field.Type == TType.Bool) {
              HasShield = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 23:
            if (field.Type == TType.Bool) {
              Shielded = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 31:
            if (field.Type == TType.I64) {
              DockedPart = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("DockingPort");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.state) {
        field.Name = "state";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)State);
        oprot.WriteFieldEnd();
      }
      if (__isset.partId) {
        field.Name = "partId";
        field.Type = TType.I64;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(PartId);
        oprot.WriteFieldEnd();
      }
      if (__isset.reEngageDistance) {
        field.Name = "reEngageDistance";
        field.Type = TType.Double;
        field.ID = 21;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(ReEngageDistance);
        oprot.WriteFieldEnd();
      }
      if (__isset.hasShield) {
        field.Name = "hasShield";
        field.Type = TType.Bool;
        field.ID = 22;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(HasShield);
        oprot.WriteFieldEnd();
      }
      if (__isset.shielded) {
        field.Name = "shielded";
        field.Type = TType.Bool;
        field.ID = 23;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Shielded);
        oprot.WriteFieldEnd();
      }
      if (__isset.dockedPart) {
        field.Name = "dockedPart";
        field.Type = TType.I64;
        field.ID = 31;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(DockedPart);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("DockingPort(");
      bool __first = true;
      if (__isset.state) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("State: ");
        __sb.Append(State);
      }
      if (__isset.partId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PartId: ");
        __sb.Append(PartId);
      }
      if (__isset.reEngageDistance) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ReEngageDistance: ");
        __sb.Append(ReEngageDistance);
      }
      if (__isset.hasShield) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HasShield: ");
        __sb.Append(HasShield);
      }
      if (__isset.shielded) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Shielded: ");
        __sb.Append(Shielded);
      }
      if (__isset.dockedPart) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DockedPart: ");
        __sb.Append(DockedPart);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
