/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum DockingPortState
  {
    Ready = 0,
    Docked = 1,
    Docking = 2,
    Undocking = 3,
    Shielded = 4,
    Moving = 5,
  }
}
