/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum EditorFacility
  {
    None = 0,
    SPH = 1,
    VAB = 2,
  }
}
