/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum GameScenes
  {
    CREDITS = 0,
    EDITOR = 1,
    FLIGHT = 2,
    LOADING = 3,
    LOADINGBUFFER = 4,
    MAINMENU = 5,
    PSYSTEM = 6,
    SETTINGS = 7,
    SPACECENTER = 8,
    TRACKSTATION = 9,
  }
}
