/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum LandingLegStates
  {
    DEPLOYED = 0,
    RETRACTED = 1,
    DEPLOYING = 2,
    RETRACTING = 3,
    BROKEN = 4,
    REPAIRING = 5,
  }
}
