/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum LandingGearStates
  {
    DEPLOYING = 0,
    DEPLOYED = 1,
    RETRACTING = 2,
    RETRACTED = 3,
    UNDEFINED = 4,
  }
}
