/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum SolarPanelState
  {
    BROKEN = 0,
    EXTENDED = 1,
    EXTENDING = 2,
    RETRACTED = 3,
    RETRACTING = 4,
  }
}
