/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum VesselType
  {
    Ship = 0,
    Station = 1,
    Lander = 2,
    Probe = 3,
    Rover = 4,
    Base = 5,
    Debris = 6,
  }
}
