/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace SKRApi
{
  public static class SKRApiConstants
  {
    public const int INT32CONSTANT = 9853;
    public static Dictionary<string, string> MAPCONSTANT = new Dictionary<string, string>();
    static SKRApiConstants()
    {
      MAPCONSTANT["hello"] = "world";
      MAPCONSTANT["goodnight"] = "moon";
    }
  }
}
