/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KerbalApi.Api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class FlightGlobals : TBase
  {
    private Vessel _activeVessel;
    private List<Vessel> _vessels;

    public Vessel ActiveVessel
    {
      get
      {
        return _activeVessel;
      }
      set
      {
        __isset.activeVessel = true;
        this._activeVessel = value;
      }
    }

    public List<Vessel> Vessels
    {
      get
      {
        return _vessels;
      }
      set
      {
        __isset.vessels = true;
        this._vessels = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool activeVessel;
      public bool vessels;
    }

    public FlightGlobals() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              ActiveVessel = new Vessel();
              ActiveVessel.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Vessels = new List<Vessel>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  Vessel _elem2;
                  _elem2 = new Vessel();
                  _elem2.Read(iprot);
                  Vessels.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("FlightGlobals");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ActiveVessel != null && __isset.activeVessel) {
        field.Name = "activeVessel";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        ActiveVessel.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Vessels != null && __isset.vessels) {
        field.Name = "vessels";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Vessels.Count));
          foreach (Vessel _iter3 in Vessels)
          {
            _iter3.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("FlightGlobals(");
      bool __first = true;
      if (ActiveVessel != null && __isset.activeVessel) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ActiveVessel: ");
        __sb.Append(ActiveVessel== null ? "<null>" : ActiveVessel.ToString());
      }
      if (Vessels != null && __isset.vessels) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Vessels: ");
        __sb.Append(Vessels);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
