/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum ParachuteState
  {
    ACTIVE = 0,
    CUT = 1,
    DEPLOYED = 2,
    SEMIDEPLOYED = 3,
    STOWED = 4,
  }
}
