/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum PartStates
  {
    ACTIVE = 0,
    DEACTIVATED = 1,
    DEAD = 2,
    IDLE = 3,
  }
}
