/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KerbalApi.Api
{
  public enum VesselSituation
  {
    DOCKED = 0,
    ESCAPING = 1,
    FLYING = 2,
    LANDED = 3,
    ORBITING = 4,
    PRELAUNCH = 5,
    SPLASHED = 6,
    SUB_ORBITAL = 7,
  }
}
