/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Radical.KerbalApi.Api
{
  public enum GameModes
  {
    CAREER = 0,
    SANDBOX = 1,
    SCENARIO = 2,
    SCENARIO_NON_RESUMABLE = 3,
    SCIENCE_SANDBOX = 4,
  }
}
